NONE = ''
BUG = 'BUG'
DARK = 'DARK'
DRAGON = 'DRAGON'
ELECTRIC = 'ELECTRIC'
FAIRY = 'FAIRY'
FIGHTING = 'FIGHTING'
FIRE = 'FIRE'
FLYING = 'FLYING'
GHOST = 'GHOST'
GRASS = 'GRASS'
GROUND = 'GROUND'
ICE = 'ICE'
NORMAL = 'NORMAL'
POISON = 'POISON'
PSYCHIC = 'PSYCHIC'
ROCK = 'ROCK'
STEEL = 'STEEL'
WATER = 'WATER'

TYPES = [
    NONE,
    BUG,
    DARK,
    DRAGON,
    ELECTRIC,
    FAIRY,
    FIGHTING,
    FIRE,
    FLYING,
    GHOST,
    GRASS,
    GROUND,
    ICE,
    NORMAL,
    POISON,
    PSYCHIC,
    ROCK,
    STEEL,
    WATER]

WEAKNESSES = {
    NONE:[],
    BUG:[FIRE, FLYING, ROCK],
    DARK:[BUG, FAIRY, FIGHTING],
    DRAGON:[DRAGON, FAIRY, ICE],
    ELECTRIC:[GROUND],
    FAIRY:[POISON, STEEL],
    FIGHTING:[FAIRY, FLYING, PSYCHIC],
    FIRE:[GROUND, ROCK, WATER],
    FLYING:[ELECTRIC, ICE, ROCK],
    GHOST:[DARK, GHOST],
    GRASS:[BUG, FIRE, FLYING, ICE, POISON],
    GROUND:[GRASS, ICE, WATER],
    ICE:[FIGHTING, FIRE, ROCK, STEEL],
    NORMAL:[FIGHTING],
    POISON:[GROUND, PSYCHIC],
    PSYCHIC:[BUG, DARK, GHOST],
    ROCK:[FIGHTING, GRASS, GROUND, STEEL, WATER],
    STEEL:[FIGHTING, FIRE, GROUND],
    WATER:[ELECTRIC, GRASS]}

RESISTANCES = {
    NONE:[],
    BUG:[FIGHTING, GRASS, GROUND],
    DARK:[DARK, GHOST, PSYCHIC],
    DRAGON:[ELECTRIC, FIRE, GRASS, WATER],
    ELECTRIC:[ELECTRIC, FLYING, STEEL],
    FAIRY:[BUG, DARK, DRAGON, FIGHTING],
    FIGHTING:[BUG, DARK, ROCK],
    FIRE:[BUG, FAIRY, FIRE, GRASS, ICE, STEEL],
    FLYING:[BUG, FIGHTING, GRASS, GROUND],
    GHOST:[BUG, FIGHTING, NORMAL, NORMAL],
    GRASS:[ELECTRIC, GRASS, GROUND, WATER],
    GROUND:[ELECTRIC, POISON, ROCK],
    ICE:[ICE],
    NORMAL:[GHOST],
    POISON:[BUG, FAIRY, FIGHTING, GRASS, POISON],
    PSYCHIC:[FIGHTING, PSYCHIC],
    ROCK:[FIRE, FLYING, NORMAL, POISON],
    STEEL:[BUG, DRAGON, FAIRY, FLYING, GRASS, ICE, NORMAL, POISON, PSYCHIC, ROCK, STEEL],
    WATER:[FIRE, ICE, STEEL, WATER]}

POKEMON_DB = {
    'BULBASAUR'                 :[GRASS     , POISON],
    'IVYSAUR'                   :[GRASS     , POISON],
    'VENUSAUR'                  :[GRASS     , POISON],
    'CHARMANDER'                :[FIRE      , NONE],
    'CHARMELEON'                :[FIRE      , NONE],
    'CHARIZARD'                 :[FIRE      , FLYING],
    'SQUIRTLE'                  :[WATER     , NONE],
    'WARTORTLE'                 :[WATER     , NONE],
    'BLASTOISE'                 :[WATER     , NONE],
    'CATERPIE'                  :[BUG       , NONE],
    'METAPOD'                   :[BUG       , NONE],
    'BUTTERFREE'                :[BUG       , FLYING],
    'WEEDLE'                    :[BUG       , POISON],
    'KAKUNA'                    :[BUG       , POISON],
    'BEEDRILL'                  :[BUG       , POISON],
    'PIDGEY'                    :[NORMAL    , FLYING],
    'PIDGEOTTO'                 :[NORMAL    , FLYING],
    'PIDGEOT'                   :[NORMAL    , FLYING],
    'RATTATA'                   :[NORMAL    , NONE],
    'RATTATA (ALOLAN)'          :[DARK      , NORMAL],
    'RATICATE'                  :[NORMAL    , NONE],
    'RATICATE (ALOLAN)'         :[DARK      , NORMAL],
    'SPEAROW'                   :[NORMAL    , FLYING],
    'FEAROW'                    :[NORMAL    , FLYING],
    'EKANS'                     :[POISON    , NONE],
    'ARBOK'                     :[POISON    , NONE],
    'PIKACHU'                   :[ELECTRIC  , NONE],
    'RAICHU'                    :[ELECTRIC  , NONE],
    'RAICHU (ALOLAN)'           :[ELECTRIC  , PSYCHIC],
    'SANDSHREW'                 :[GROUND    , NONE],
    'SANDSHREW (ALOLAN)'        :[ICE       , STEEL],
    'SANDSLASH'                 :[GROUND    , NONE],
    'SANDSLASH (ALOLAN)'        :[ICE       , STEEL],
    'NIDORAN F'                 :[POISON    , NONE],
    'NIDORINA'                  :[POISON    , NONE],
    'NIDOQUEEN'                 :[POISON    , GROUND],
    'NIDORAN M'                 :[POISON    , NONE],
    'NIDORINO'                  :[POISON    , NONE],
    'NIDOKING'                  :[POISON    , GROUND],
    'CLEFAIRY'                  :[FAIRY     , NONE],
    'CLEFABLE'                  :[FAIRY     , NONE],
    'VULPIX'                    :[FIRE      , NONE],
    'VULPIX (ALOLAN)'           :[ICE       , NONE],
    'NINETAILS'                 :[FIRE      , NONE],
    'NINETAILS (ALOLAN)'        :[ICE       , FAIRY],
    'JIGGLYPUFF'                :[NORMAL    , FAIRY],
    'WIGGLYTUFF'                :[NORMAL    , FAIRY],
    'ZUBAT'                     :[POISON    , FLYING],
    'GOLBAT'                    :[POISON    , FLYING],
    'ODDISH'                    :[GRASS     , POISON],
    'GLOOM'                     :[GRASS     , POISON],
    'VILEPLUME'                 :[GRASS     , POISON],
    'PARAS'                     :[BUG       , GRASS],
    'PARASECT'                  :[BUG       , GRASS],
    'VENONAT'                   :[BUG       , POISON],
    'VENOMOTH'                  :[BUG       , POISON],
    'DIGLETT'                   :[GROUND    , NONE],
    'DIGLETT (ALOLAN)'          :[GROUND    , STEEL],
    'DUGTRIO'                   :[GROUND    , NONE],
    'DUGTRIO (ALOLAN)'          :[GROUND    , STEEL],
    'MEOWTH'                    :[NORMAL    , NONE],
    'MEOWTH (ALOLAN)'           :[DARK      , NONE],
    'MEOWTH (GALARIAN)'         :[STEEL     , NONE],
    'PERSIAN'                   :[NORMAL    , NONE],
    'PERSIAN (ALOLAN)'          :[DARK      , NONE],
    'PSYDUCK'                   :[WATER     , NONE],
    'GOLDUCK'                   :[WATER     , NONE],
    'MANKEY'                    :[FIGHTING  , NONE],
    'PRIMEAPE'                  :[FIGHTING  , NONE],
    'GROWLITHE'                 :[FIRE      , NONE],
    'GROWLITHE (HISUIAN)'       :[FIRE      , ROCK],
    'ARCANINE'                  :[FIRE      , NONE],
    'ARCANINE (HISUIAN)'        :[FIRE      , ROCK],
    'POLIWAG'                   :[WATER     , NONE],
    'POLIWHIRL'                 :[WATER     , NONE],
    'POLIWRATH'                 :[WATER     , FIGHTING],
    'ABRA'                      :[PSYCHIC   , NONE],
    'KADABRA'                   :[PSYCHIC   , NONE],
    'ALAKAZAM'                  :[PSYCHIC   , NONE],
    'MACHOP'                    :[FIGHTING  , NONE],
    'MACHOKE'                   :[FIGHTING  , NONE],
    'MACHAMP'                   :[FIGHTING  , NONE],
    'BELLSPROUT'                :[GRASS     , POISON],
    'WEEPINBELL'                :[GRASS     , POISON],
    'VICTREEBEL'                :[GRASS     , POISON],
    'TENTACOOL'                 :[WATER     , POISON],
    'TENTACRUEL'                :[WATER     , POISON],
    'GEODUDE'                   :[ROCK      , GROUND],
    'GEODUDE (ALOLAN)'          :[ROCK      , ELECTRIC],
    'GRAVELER'                  :[ROCK      , GROUND],
    'GRAVELER (ALOLAN)'         :[ROCK      , ELECTRIC],
    'GOLEM'                     :[ROCK      , GROUND],
    'GOLEM (ALOLAN)'            :[ROCK      , ELECTRIC],
    'PONYTA'                    :[FIRE      , NONE],
    'PONYTA (GALARIAN)'         :[PSYCHIC   , NONE],
    'RAPIDASH'                  :[FIRE      , NONE],
    'RAPIDASH (GALARIAN)'       :[PSYCHIC   , FAIRY],
    'SLOWPOKE'                  :[WATER     , PSYCHIC],
    'SLOWPOKE (GALARIAN)'       :[PSYCHIC   , NONE],
    'SLOWBRO'                   :[WATER     , PSYCHIC],
    'SLOWBRO (GALARIAN)'        :[POISON    , PSYCHIC],
    'MAGNEMITE'                 :[ELECTRIC  , STEEL],
    'MAGNETON'                  :[ELECTRIC  , STEEL],
    'FARFETCH\'D'               :[NORMAL    , FLYING],
    'FARFETCH\'D (GALARIAN)'    :[FIGHTING  , NONE],
    'DODUO'                     :[NORMAL    , FLYING],
    'DODRIO'                    :[NORMAL    , FLYING],
    'SEEL'                      :[WATER     , NONE],
    'DEWGONG'                   :[WATER     , ICE],
    'GRIMER'                    :[POISON    , NONE],
    'GRIMER (ALOLAN)'           :[POISON    , DARK],
    'MUK'                       :[POISON    , NONE],
    'MUK'                       :[POISON    , DARK],
    'SHELLDER'                  :[WATER     , NONE],
    'CLOYSTER'                  :[WATER     , ICE],
    'GASTLY'                    :[GHOST     , POISON],
    'HAUNTER'                   :[GHOST     , POISON],
    'GENGAR'                    :[GHOST     , POISON],
    'ONIX'                      :[ROCK      , GROUND],
    'DROWZEE'                   :[PSYCHIC   , NONE],
    'HYPNO'                     :[PSYCHIC   , NONE],
    'KRABBY'                    :[WATER     , NONE],
    'KINGLER'                   :[WATER     , NONE],
    'VOLTORB'                   :[ELECTRIC  , NONE],
    'VOLTORB (HISUIAN)'         :[ELECTRIC  , GRASS],
    'ELECTrODE'                 :[ELECTRIC  , NONE],
    'ELECTRODE (HISUIAN)'       :[ELECTRIC  , GRASS],
    'EXEGGCUTE'                 :[GRASS     , PSYCHIC],
    'EXEGGUTOR'                 :[GRASS     , PSYCHIC],
    'EXEGGUTOR (ALOLAN)'        :[GRASS     , DRAGON],
    'CUBONE'                    :[GROUND    , NONE],
    'MAROWAK'                   :[GROUND    , NONE],
    'MAROWAK (ALOLAN)'          :[FIRE      , GHOST],
    'HITMONLEE'                 :[FIGHTING  , NONE],
    'HITMONCHAN'                :[FIGHTING  , NONE],
    'LICKITUNG'                 :[NORMAL    , NONE],
    'KOFFING'                   :[POISON    , NONE],
    'WEEZING'                   :[POISON    , NONE],
    'WEEZING (GALARIAN)'        :[POISON    , FAIRY],
    'RYHORN'                    :[GROUND    , ROCK],
    'RHYDON'                    :[GROUND    , ROCK],
    'CHANSEY'                   :[NORMAL    , NONE],
    'TANGELA'                   :[GRASS     , NONE],
    'KANGASKHAN'                :[NORMAL    , NONE],
    'HORSEA'                    :[WATER     , NONE],
    'SEADRA'                    :[WATER     , NONE],
    'GOLDEEN'                   :[WATER     , NONE],
    'SEAKING'                   :[WATER     , NONE],
    'STARYU'                    :[WATER     , NONE],
    'STARMIE'                   :[WATER     , PSYCHIC],
    'MR. MIME'                  :[PSYCHIC   , FAIRY],
    'MR. MIME (GALARIAN)'       :[ICE       , PSYCHIC],
    'SCYTHER'                   :[BUG       , FLYING],
    'JYNX'                      :[ICE       , PSYCHIC],
    'ELECTABUZZ'                :[ELECTRIC  , NONE],
    'MAGMAR'                    :[FIRE      , NONE],
    'PINSIR'                    :[BUG       , NONE],
    'TAUROS'                    :[NORMAL    , NONE],
    'TAUROS (PALDEAN)(COMBAT)'  :[FIGHTING  , NONE],
    'TAUROS (PALDEAN)(BLAZE)'   :[FIGHTING  , FIRE],
    'TAUROS (PALDEAN)(AQUA)'    :[FIGHTING  , WATER],
    'MAGIKARP'                  :[WATER     , NONE],
    'GYARADOS'                  :[WATER     , FLYING],
    'LAPRAS'                    :[WATER     , ICE],
    'DITTO'                     :[NORMAL    , NONE],
    'EEVEE'                     :[NORMAL    , NONE],
    'VAPOREON'                  :[WATER     , NONE],
    'JOLTEON'                   :[ELECTRIC  , NONE],
    'FLAREON'                   :[FIRE      , NONE],
    'PORYGON'                   :[NORMAL    , NONE],
    'OMANYTE'                   :[ROCK      , WATER],
    'OMASTAR'                   :[ROCK      , WATER],
    'KABUTO'                    :[ROCK      , WATER],
    'KABUTOPS'                  :[ROCK      , WATER],
    'AERODACTYL'                :[ROCK      , FLYING],
    'SNORLAX'                   :[NORMAL    , NONE],
    'ARTICUNO'                  :[ICE       , FLYING],
    'ARTICUNO (GALARIAN)'       :[PSYCHIC   , FLYING],
    'ZAPDOS'                    :[ELECTRIC  , FLYING],
    'ZAPDOS (GALARIAN)'         :[FIGHTING  , FLYING],
    'MOLTRES'                   :[FIRE      , FLYING],
    'MOLTRES (GALARIAN)'        :[DARK      , FLYING],
    'DRATINI'                   :[DRAGON    , NONE],
    'DRAGONAIR'                 :[DRAGON    , NONE],
    'DRAGONITE'                 :[DRAGON    , FLYING],
    'MEWTWO'                    :[PSYCHIC   , NONE],
    'MEW'                       :[PSYCHIC   , NONE],





    'CHIKORITA'                 :[GRASS     , NONE],
    'BAYLEEF'                   :[GRASS     , NONE],
    'MEGANIUM'                  :[GRASS     , NONE],
    'CYNDAQUILL'                :[FIRE      , NONE],
    'QUILAVA'                   :[FIRE      , NONE],
    'TYPHLOSION'                :[FIRE      , NONE],
    'TYPHLOSION (HISUIAN)'      :[FIRE      , GHOST],
    'TOTODILE'                  :[WATER     , NONE],
    'CROCOMAW'                  :[WATER     , NONE],
    'FERALIGATR'                :[WATER     , NONE],
    'SENTRET'                   :[NORMAL    , NONE],
    'FURRET'                    :[NORMAL    , NONE],
    'HOOTHOOT'                  :[NORMAL    , FLYING],
    'NOCTOWL'                   :[NORMAL    , FLYING],
    'LEDYBA'                    :[BUG       , FLYING],
    'LEDIAN'                    :[BUG       , FLYING],
    'SPINARAK'                  :[BUG       , POISON],
    'ARIADOS'                   :[BUG       , POISON],
    'CROBAT'                    :[POISON    , FLYING],
    'CHINCHOU'                  :[WATER     , ELECTRIC],
    'LANTURN'                   :[WATER     , ELECTRIC],
    'PICHU'                     :[ELECTRIC  , NONE],
    'CLEFFA'                    :[FAIRY     , NONE],
    'IGGLYBUFF'                 :[NORMAL    , FAIRY],
    'TOGEPI'                    :[FAIRY     , NONE],
    'TOGETIC'                   :[FAIRY     , FLYING],
    'NATU'                      :[PSYCHIC   , FLYING],
    'XATU'                      :[PSYCHIC   , FLYING],
    'MAREEP'                    :[ELECTRIC  , NONE],
    'FLAAFFY'                   :[ELECTRIC  , NONE],
    'AMPHAROS'                  :[ELECTRIC  , NONE],
    'BELLOSSOM'                 :[GRASS     , NONE],
    'MARILL'                    :[WATER     , FAIRY],
    'AZUMARILL'                 :[WATER     , FAIRY],
    'SUDOWOODO'                 :[ROCK      , NONE],
    'POLITOED'                  :[WATER     , NONE],
    'HOPPIP'                    :[GRASS     , FLYING],
    'SKIPLOOM'                  :[GRASS     , FLYING],
    'JUMPLUFF'                  :[GRASS     , FLYING],
    'AIPOM'                     :[NORMAL    , NONE],
    'SUNKERN'                   :[GRASS     , NONE],
    'SUNFLORA'                  :[GRASS     , NONE],
    'YANMA'                     :[BUG       , FLYING],
    'WOOPER'                    :[WATER     , GROUND],
    'WOOPER (PALDEAN)'          :[POISON    , GROUND],
    'QUAGSIRE'                  :[WATER     , GROUND],
    'ESPEON'                    :[PSYCHIC   , NONE],
    'UMBREON'                   :[DARK      , NONE],
    'MURKROW'                   :[DARK      , NONE],
    'SLOWKING'                  :[WATER     , PSYCHIC],
    'SLOWKING (GALARIAN)'       :[POISON    , PSYCHIC],
    'MISDREAVUS'                :[GHOST     , NONE],
    'UNOWN'                     :[PSYCHIC   , NONE],
    'WOBBUFFET'                 :[PSYCHIC   , NONE],
    'GIRAFARIG'                 :[NORMAL    , PSYCHIC],
    'PINECO'                    :[BUG       , NONE],
    'FORRETRESS'                :[BUG       , STEEL],
    'DUNSPARCE'                 :[NORMAL    , NONE],
    'GLIGAR'                    :[GROUND    , FLYING],
    'STEELIX'                   :[STEEL     , GROUND],
    'SNUBBULL'                  :[FAIRY     , NONE],
    'GRANBULL'                  :[FAIRY     , NONE],
    'QWILFISH'                  :[WATER     , POISON],
    'QWILFISH (HISUIAN)'        :[DARK      , POISON],
    'SCIZOR'                    :[BUG       , STEEL],
    'SHUCKLE'                   :[BUG       , ROCK],
    'HERACROSS'                 :[BUG       , FIGHTING],
    'SNEASEL'                   :[DARK      , ICE],
    'SNEASEL (HISUIAN)'         :[FIGHTING  , POISON],
    'TEDDIURSA'                 :[NORMAL    , NONE],
    'URSARING'                  :[NORMAL    , NONE],
    'SLUGMA'                    :[FIRE      , NONE],
    'MAGCARGO'                  :[FIRE      , ROCK],
    'SWINUB'                    :[ICE       , GROUND],
    'PILOSWINE'                 :[ICE       , GROUND],
    'CORSOLA'                   :[WATER     , ROCK],
    'CORSOLA (GALARIAN)'        :[GHOST     , NONE],
    'REMORAID'                  :[WATER     , NONE],
    'OCTILLERY'                 :[WATER     , NONE],
    'DELIBIRD'                  :[ICE       , FLYING],
    'MANTINE'                   :[WATER     , FLYING],
    'SKARMORY'                  :[STEEL     , FLYING],
    'HOUNDOUR'                  :[DARK      , FIRE],
    'HOUNDOOM'                  :[DARK      , FIRE],
    'KINGDRA'                   :[WATER     , DRAGON],
    'PHANPY'                    :[GROUND    , NONE],
    'DONPHAN'                   :[GROUND    , NONE],
    'PORYGON2'                  :[NORMAL    , NONE],
    'STANTLER'                  :[NORMAL    , NONE],
    'SMEARGLE'                  :[NORMAL    , NONE],
    'TYROGUE'                   :[FIGHTING  , NONE],
    'HITMONTOP'                 :[FIGHTING  , NONE],
    'SMOOCHUM'                  :[ICE       , PSYCHIC],
    'ELEKID'                    :[ELECTRIC  , NONE],
    'MAGBY'                     :[FIRE      , NONE],
    'MILTANK'                   :[NORMAL    , NONE],
    'BLISSEY'                   :[NORMAL    , NONE],
    'RAIKOU'                    :[ELECTRIC  , NONE],
    'ENTEI'                     :[FIRE      , NONE],
    'SUICUNE'                   :[WATER     , NONE],
    'LARVITAR'                  :[ROCK      , GROUND],
    'PUPITAR'                   :[ROCK      , GROUND],
    'TYRANITAR'                 :[ROCK      , DARK],
    'LUGIA'                     :[PSYCHIC   , FLYING],
    'HO-OH'                     :[FIRE      , FLYING],
    'CELEBI'                    :[PSYCHIC   , GRASS],





    'TREECKO'                   :[GRASS     , NONE],
    'GROVYLE'                   :[GRASS     , NONE],
    'SCEPTILE'                  :[GRASS     , NONE],
    'TORCHIC'                   :[FIRE      , NONE],
    'COMBUSKEN'                 :[FIRE      , FIGHTING],
    'BLAZIKEN'                  :[FIRE      , FIGHTING],
    'MUDKIP'                    :[WATER     , NONE],
    'MARSHTOMP'                 :[WATER     , GROUND],
    'SWAMPERT'                  :[WATER     , GROUND],
    'POOCHYENA'                 :[DARK      , NONE],
    'MIGHTYENA'                 :[DARK      , NONE],
    'ZIGZAGOON'                 :[NORMAL    , NONE],
    'ZIGZAGOON (GALARIAN)'      :[DARK      , NORMAL],
    'LINOONE'                   :[NORMAL    , NONE],
    'LINOONE (GALARIAN)'        :[DARK      , NORMAL],
    'WURMPLE'                   :[BUG       , NONE],
    'SILCOON'                   :[BUG       , NONE],
    'BEAUTIFLY'                 :[BUG       , FLYING],
    'CASCOON'                   :[BUG       , NONE],
    'DUSTOX'                    :[BUG       , POISON],
    'LOTAD'                     :[WATER     , GRASS],
    'LOMBRE'                    :[WATER     , GRASS],
    'LUDICOLO'                  :[WATER     , GRASS],
    'SEEDOT'                    :[GRASS     , NONE],
    'NUZLEAF'                   :[GRASS     , DARK],
    'SHIFTRY'                   :[GRASS     , DARK],
    'TAILLOW'                   :[NORMAL    , FLYING],
    'SWELLOW'                   :[NORMAL    , FLYING],
    'WINGULL'                   :[WATER     , FLYING],
    'PELIPPER'                  :[WATER     , FLYING],
    'RALTS'                     :[PSYCHIC   , FAIRY],
    'KIRLIA'                    :[PSYCHIC   , FAIRY],
    'GARDEVOIR'                 :[PSYCHIC   , FAIRY],
    'SURSKIT'                   :[BUG       , WATER],
    'MASQUERAIN'                :[BUG       , FLYING],
    'SHROOMISH'                 :[GRASS     , NONE],
    'BRELOOM'                   :[GRASS     , FIGHTING],
    'SLAKOTH'                   :[NORMAL    , NONE],
    'VIGOROTH'                  :[NORMAL    , NONE],
    'SLAKING'                   :[NORMAL    , NONE],
    'NINCADA'                   :[BUG       , GROUND],
    'NINJASK'                   :[BUG       , FLYING],
    'SHEDINJA'                  :[BUG       , GHOST],
    'WHISMUR'                   :[NORMAL    , NONE],
    'LOUDRED'                   :[NORMAL    , NONE],
    'EXPLOUD'                   :[NORMAL    , NONE],
    'MAKUHITA'                  :[FIGHTING  , NONE],
    'HARIYAMA'                  :[FIGHTING  , NONE],
    'AZURILL'                   :[NORMAL    , FAIRY],
    'NOSEPASS'                  :[ROCK      , NONE],
    'SKITTY'                    :[NORMAL    , NONE],
    'DELCATTY'                  :[NORMAL    , NONE],
    'SABLEYE'                   :[DARK      , GHOST],
    'MAWILE'                    :[STEEL     , FAIRY],
    'ARON'                      :[STEEL     , ROCK],
    'LAIRON'                    :[STEEL     , ROCK],
    'AGGRON'                    :[STEEL     , ROCK],
    'MEDITITE'                  :[FIGHTING  , PSYCHIC],
    'MEDICHAM'                  :[FIGHTING  , PSYCHIC],
    'ELECTRIKE'                 :[ELECTRIC  , NONE],
    'MANECTRIC'                 :[ELECTRIC  , NONE],
    'PLUSLE'                    :[ELECTRIC  , NONE],
    'MINUN'                     :[ELECTRIC  , NONE],
    'VOLBEAT'                   :[BUG       , NONE],
    'ILLUMISE'                  :[BUG       , NONE],
    'ROSELIA'                   :[GRASS     , POISON],
    'GULPIN'                    :[POISON    , NONE],
    'SWALOT'                    :[POISON    , NONE],
    'CARVANHA'                  :[WATER     , DARK],
    'SHARPEDO'                  :[WATER     , DARK],
    'WAILMER'                   :[WATER     , NONE],
    'WAILORD'                   :[WATER     , NONE],
    'NUMEL'                     :[FIRE      , GROUND],
    'CAMERUPT'                  :[FIRE      , GROUND],
    'TORKOAL'                   :[FIRE      , NONE],
    'SPOINK'                    :[PSYCHIC   , NONE],
    'GRUMPIG'                   :[PSYCHIC   , NONE],
    'SPINDA'                    :[NORMAL    , NONE],
    'TRAPINCH'                  :[GROUND    , NONE],
    'VIBRAVA'                   :[GROUND    , DRAGON],
    'FLYGON'                    :[GROUND    , DRAGON],
    'CACNEA'                    :[GRASS     , NONE],
    'CACTURNE'                  :[GRASS     , DARK],
    'SWABLU'                    :[NORMAL    , FLYING],
    'ALTARIA'                   :[DRAGON    , FLYING],
    'ZANGOOSE'                  :[NORMAL    , NONE],
    'SEVIPER'                   :[POISON    , NONE],
    'LUNASTONE'                 :[ROCK      , PSYCHIC],
    'SOLROCK'                   :[ROCK      , PSYCHIC],
    'BARBOACH'                  :[WATER     , GROUND],
    'WHISCASH'                  :[WATER     , GROUND],
    'CORPHISH'                  :[WATER     , NONE],
    'CRAWDAUNT'                 :[WATER     , DARK],
    'BALTOY'                    :[GROUND    , PSYCHIC],
    'CLAYDOL'                   :[GROUND    , PSYCHIC],
    'LILEEP'                    :[ROCK      , GRASS],
    'CRADILY'                   :[ROCK      , GRASS],
    'ANORITH'                   :[ROCK      , BUG],
    'ARMALDO'                   :[ROCK      , BUG],
    'FEEBAS'                    :[WATER     , NONE],
    'MILOTIC'                   :[WATER     , NONE],
    'CASTFORM (NORMAL)'         :[NORMAL    , NONE],
    'CASTFORM (SUNNY)'          :[FIRE      , NONE],
    'CASTFORM (RAINY)'          :[WATER     , NONE],
    'CASTFORM (SNOWY)'          :[ICE       , NONE],
    'KECLEON'                   :[NORMAL    , NONE],
    'SHUPPET'                   :[GHOST     , NONE],
    'BANETTE'                   :[GHOST     , NONE],
    'DUSKULL'                   :[GHOST     , NONE],
    'DUSCLOPS'                  :[GHOST     , NONE],
    'TROPIUS'                   :[GRASS     , FLYING],
    'CHIMECHO'                  :[PSYCHIC   , NONE],
    'ABSOL'                     :[DARK      , NONE],
    'WYNAUT'                    :[PSYCHIC   , NONE],
    'SNORUNT'                   :[ICE       , NONE],
    'GLALIE'                    :[ICE       , NONE],
    'SPHEAL'                    :[ICE       , WATER],
    'SEALEO'                    :[ICE       , WATER],
    'WALREIN'                   :[ICE       , WATER],
    'CLAMPERL'                  :[WATER     , NONE],
    'HUNTAIL'                   :[WATER     , NONE],
    'GOREBYSS'                  :[WATER     , NONE],
    'RELICANTH'                 :[WATER     , ROCK],
    'LUVDISC'                   :[WATER     , NONE],
    'BAGON'                     :[DRAGON    , NONE],
    'SHELGON'                   :[DRAGON    , NONE],
    'SALAMANCE'                 :[DRAGON    , FLYING],
    'BELDUM'                    :[STEEL     , PSYCHIC],
    'METANG'                    :[STEEL     , PSYCHIC],
    'METAGROSS'                 :[STEEL     , PSYCHIC],
    'REGIROCK'                  :[ROCK      , NONE],
    'REGICE'                    :[ICE       , NONE],
    'REGISTEEL'                 :[STEEL     , NONE],
    'LATIAS'                    :[DRAGON    , PSYCHIC],
    'LATIOS'                    :[DRAGON    , PSYCHIC],
    'KYOGRE'                    :[WATER     , NONE],
    'GROUDON'                   :[GROUND    , NONE],
    'RAYQUAZA'                  :[DRAGON    , FLYING],
    'JIRACHI'                   :[STEEL     , PSYCHIC],
    'DEOXYS (NORMAL)'           :[PSYCHIC   , NONE],
    'DEOXYS (ATTACK)'           :[PSYCHIC   , NONE],
    'DEOXYS (DEFENSE)'          :[PSYCHIC   , NONE],
    'DEOXYS (SPEED)'            :[PSYCHIC   , NONE],





    'TURTWIG'                   :[GRASS     , NONE],
    'GROTLE'                    :[GRASS     , NONE],
    'TORTERRA'                  :[GRASS     , GROUND],
    'CHIMCHAR'                  :[FIRE      , NONE],
    'MONFERNO'                  :[FIRE      , FIGHTING],
    'INFERNAPE'                 :[FIRE      , FIGHTING],
    'PIPLUP'                    :[WATER     , NONE],
    'PRINPLUP'                  :[WATER     , NONE],
    'EMPOLEON'                  :[WATER     , STEEL],
    'STARLY'                    :[NORMAL    , FLYING],
    'STARAVIA'                  :[NORMAL    , FLYING],
    'STARAPTOR'                 :[NORMAL    , FLYING],
    'BIDOOF'                    :[NORMAL    , NONE],
    'BIBAREL'                   :[NORMAL    , WATER],
    'KRICKETOT'                 :[BUG       , NONE],
    'KRICKETUNE'                :[BUG       , NONE],
    'SHINX'                     :[ELECTRIC  , NONE],
    'LUXIO'                     :[ELECTRIC  , NONE],
    'LUXRAY'                    :[ELECTRIC  , NONE],
    'BUDWEW'                    :[GRASS     , POISON],
    'ROSERADE'                  :[GRASS     , POISON],
    'CRANIDOS'                  :[ROCK      , NONE],
    'RAMPARDOS'                 :[ROCK      , NONE],
    'SHIELDON'                  :[ROCK      , STEEL],
    'BASTIDON'                  :[ROCK      , STEEL],
    'BURMY (PLANT)'             :[BUG       , NONE],
    'BURMY (SANDY)'             :[BUG       , NONE],
    'BURMY (TRASH)'             :[BUG       , NONE],
    'WORMADAM (PLANT)'          :[BUG       , GRASS],
    'WORMADAM (SANDY)'          :[BUG       , GROUND],
    'WORMADAM (tRASH)'          :[BUG       , STEEL],
    'MOTHIM'                    :[BUG       , FLYING],
    'COMBEE'                    :[BUG       , FLYING],
    'VESPIQUEN'                 :[BUG       , FLYING],
    'PACHIRISU'                 :[ELECTRIC  , NONE],
    'BUIZEL'                    :[WATER     , NONE],
    'FLOATZEL'                  :[WATER     , NONE],
    'CHERUBI'                   :[GRASS     , NONE],
    'CHERRIM (OVERCAST)'        :[GRASS     , NONE],
    'CHERRIM (SUNSHINE)'        :[GRASS     , NONE],
    'SHELIOS (WEST)'            :[WATER     , NONE],
    'SHELIOS (EAST)'            :[WATER     , NONE],
    'GASTRODON (WEST)'          :[WATER     , GROUND],
    'GASTRODON (EAST)'          :[WATER     , GROUND],
    'AMBIPOM'                   :[NORMAL    , NONE],
    'DRIFLOON'                  :[GHOST     , FLYING],
    'DRIFBLIM'                  :[GHOST     , FLYING],
    'BUNEARY'                   :[NORMAL    , NONE],
    'LOPUNNY'                   :[NORMAL    , NONE],
    'MISMAGIUS'                 :[GHOST     , NONE],
    'HONCHKROW'                 :[DARK      , FLYING],
    'GLAMEOW'                   :[NORMAL    , NONE],
    'PURUGLY'                   :[NORMAL    , NONE],
    'CHINGLING'                 :[PSYCHIC   , NONE],
    'STUNKY'                    :[POISON    , DARK],
    'SKUNTANK'                  :[POISON    , DARK],
    'BRONZOR'                   :[STEEL     , PSYCHIC],
    'BRONZONG'                  :[STEEL     , PSYCHIC],
    'BONSLY'                    :[ROCK      , NONE],
    'MIME JR.'                  :[PSYCHIC   , FAIRY],
    'HAPPINY'                   :[NORMAL    , NONE],
    'CHALOT'                    :[NORMAL    , FLYING],
    'SPIRITOMB'                 :[GHOST     , DARK],
    'GIBLE'                     :[DRAGON    , GROUND],
    'GABITE'                    :[DRAGON    , GROUND],
    'GARCHOMP'                  :[DRAGON    , GROUND],
    'MUNCHLAX'                  :[NORMAL    , NONE],
    'RIOLU'                     :[FIGHTING  , NONE],
    'LUCARIO'                   :[FIGHTING  , STEEL],
    'HIPPOPOTAS'                :[GROUND    , NONE],
    'HIPPOWDON'                 :[GROUND    , NONE],
    'SKORUPI'                   :[POISON    , BUG],
    'DRAPION'                   :[POISON    , DARK],
    'CROAGUNK'                  :[POISON    , FIGHTING],
    'TOXICROAK'                 :[POISON    , FIGHTING],
    'CARNIVINE'                 :[GRASS     , NONE],
    'FINNEON'                   :[WATER     , NONE],
    'LUMINEON'                  :[WATER     , NONE],
    'MANTYKE'                   :[WATER     , FLYING],
    'SNOVER'                    :[GRASS     , ICE],
    'ABOMASNOW'                 :[GRASS     , ICE],
    'WEAVILE'                   :[DARK      , ICE],
    'MAGNEZONE'                 :[ELECTRIC  , STEEL],
    'LICKILICKY'                :[NORMAL    , NONE],
    'RHYPERIOR'                 :[GROUND    , ROCK],
    'TANGROWTH'                 :[GRASS     , NONE],
    'ELECTIVIRE'                :[ELECTRIC  , NONE],
    'MAGMORTAR'                 :[FIRE      , NONE],
    'TOGEKISS'                  :[FAIRY     , FLYING],
    'YANMEGA'                   :[BUG       , FLYING],
    'LEAFEON'                   :[GRASS     , NONE],
    'GLACEON'                   :[ICE       , NONE],
    'GLISCOR'                   :[GROUND    , FLYING],
    'MAMOSWINE'                 :[ICE       , GROUND],
    'PORYGON-Z'                 :[NORMAL    , NONE],
    'GALLADE'                   :[PSYCHIC   , FIGHTING],
    'PROBOPASS'                 :[ROCK      , STEEL],
    'DUSKNOIR'                  :[GHOST     , NONE],
    'FROSLASS'                  :[ICE       , GHOST],
    'ROTOM'                     :[ELECTRIC  , GHOST],
    'ROTOM (HEAT)'              :[ELECTRIC  , FIRE],
    'ROTOM (WASH)'              :[ELECTRIC  , WATER],
    'ROTOM (FROST)'             :[ELECTRIC  , ICE],
    'ROTOM (FAN)'               :[ELECTRIC  , FLYING],
    'ROTOM (MOW)'               :[ELECTRIC  , GRASS],
    'UXIE'                      :[PSYCHIC   , NONE],
    'MESPRIT'                   :[PSYCHIC   , NONE],
    'AZELF'                     :[PSYCHIC   , NONE],
    'DIALGA'                    :[STEEL     , DRAGON],
    'DIALGA (ORIGIN)'           :[STEEL     , DRAGON],
    'PALKIA'                    :[WATER     , DRAGON],
    'PALKIA (ORIGIN)'           :[WATER     , DRAGON],
    'HEATRAN'                   :[FIRE      , STEEL],
    'REGIGIGAS'                 :[NORMAL    , NONE],
    'GIRATINA (ALTERED)'        :[GHOST     , DRAGON],
    'GIRATINA (ORIGIN)'         :[GHOST     , DRAGON],
    'CRESSELIA'                 :[PSYCHIC   , NONE],
    'PHIONE'                    :[WATER     , NONE],
    'MANAPHY'                   :[WATER     , NONE],
    'DARKAI'                    :[DARK      , NONE],
    'SHAYMIN (LAND)'            :[GRASS     , NONE],
    'SHAYMIN (SKY)'             :[GRASS     , FLYING],
    'ARCEUS'                    :[NORMAL    , NONE],





    'VICTINI'                   :[PSYCHIC   , FIRE],
    'SNIVY'                     :[GRASS     , NONE],
    'SERVINE'                   :[GRASS     , NONE],
    'SERPERIOR'                 :[GRASS     , NONE],
    'TEPIG'                     :[FIRE      , NONE],
    'PIGNITE'                   :[FIRE      , FIGHTING],
    'EMBOAR'                    :[FIRE      , FIGHTING],
    'OSHAWOTT'                  :[WATER     , NONE],
    'DEWOTT'                    :[WATER     , NONE],
    'SAMUROTT'                  :[WATER     , NONE],
    'SAMUROTT (HISUIAN)'        :[WATER     , DARK],
    'PATRAT'                    :[NORMAL    , NONE],
    'WATCHOG'                   :[NORMAL    , NONE],
    'LILLIPUP'                  :[NORMAL    , NONE],
    'HERDIER'                   :[NORMAL    , NONE],
    'STOUTLAND'                 :[NORMAL    , NONE],
    'PURRLOIN'                  :[DARK      , NONE],
    'LIEPARD'                   :[DARK      , NONE],
    'PANSAGE'                   :[GRASS     , NONE],
    'SIMISAGE'                  :[GRASS     , NONE],
    'PANSEAR'                   :[FIRE      , NONE],
    'SIMISEAR'                  :[FIRE      , NONE],
    'PANPOUR'                   :[WATER     , NONE],
    'SIMIPOUR'                  :[WATER     , NONE],
    'MUNNA'                     :[PSYCHIC   , NONE],
    'MUSHARNA'                  :[PSYCHIC   , NONE],
    'PIDOVE'                    :[NORMAL    , FLYING],
    'TRANQUILL'                 :[NORMAL    , FLYING],
    'UNFEZANT'                  :[NORMAL    , FLYING],
    'BLITZLE'                   :[ELECTRIC  , NONE],
    'ZEBSTRIKA'                 :[ELECTRIC  , NONE],
    'ROGGENROLA'                :[ROCK      , NONE],
    'BOLDORE'                   :[ROCK      , NONE],
    'GIGALITH'                  :[ROCK      , NONE],
    'WOOBAT'                    :[PSYCHIC   , FLYING],
    'SWOOBAT'                   :[PSYCHIC   , FLYING],
    'DRILBUR'                   :[GROUND    , NONE],
    'EXCADRILL'                 :[GROUND    , STEEL],
    'AUDINO'                    :[NORMAL    , NONE],
    'TIMBURR'                   :[FIGHTING  , NONE],
    'GURDURR'                   :[FIGHTING  , NONE],
    'CONKELDURR'                :[FIGHTING  , NONE],
    'TYMPOLE'                   :[WATER     , NONE],
    'PALPITOAD'                 :[WATER     , GROUND],
    'SEISMITOAD'                :[WATER     , GROUND],
    'THROH'                     :[FIGHTING  , NONE],
    'SAWK'                      :[FIGHTING  , NONE],
    'SEWADDLE'                  :[BUG       , GRASS],
    'SWADLOON'                  :[BUG       , GRASS],
    'LEAVANNY'                  :[BUG       , GRASS],
    'VENIPEDE'                  :[BUG       , POISON],
    'WHIRLIPEDE'                :[BUG       , POISON],
    'SCOLIPEDE'                 :[BUG       , POISON],
    'COTTONEE'                  :[GRASS     , FAIRY],
    'WHIMSICOTT'                :[GRASS     , FAIRY],
    'PETILIL'                   :[GRASS     , NONE],
    'LILIGANT'                  :[GRASS     , NONE],
    'LILIGANT (HISUIAN)'        :[GRASS     , FIGHTING],
    'BASCULIN (RED-STRIPED)'    :[WATER     , NONE],
    'BASCULIN (BLUE-STRIPED)'   :[WATER     , NONE],
    'BASCULIN (WHITE-STRIPED)'  :[WATER     , NONE],
    'SANDILE'                   :[GROUND    , DARK],
    'KROKOROK'                  :[GROUND    , DARK],
    'KROOKODILE'                :[GROUND    , DARK],
    'DARUMAKA'                  :[FIRE      , NONE],
    'DARUMAKA (GALARIAN)'       :[ICE       , NONE],
    'DARMANITAN (STANDARD)'     :[FIRE      , NONE],
    'DARMANITAN (ZEN)'          :[FIRE      , PSYCHIC],
    'DARMANITAN (GALARIAN)'     :[ICE       , NONE],
    'DARMANITAN (ZEN)(GALARIAN)':[ICE       , FIRE],
    'MARACTUS'                  :[GRASS     , NONE],
    'DWEBBLE'                   :[BUG       , ROCK],
    'CRUSTLE'                   :[BUG       , ROCK],
    'SCRAGGY'                   :[DARK      , FIGHTING],
    'SCRAFTY'                   :[DARK      , FIGHTING],
    'SIGILYPH'                  :[PSYCHIC   , FLYING],
    'YAMASK'                    :[GHOST     , NONE],
    'YAMASK (GALARIAN)'         :[GROUND    , GHOST],
    'COFAGRIGUS'                :[GHOST     , NONE],
    'TIRTOUGA'                  :[WATER     , ROCK],
    'CARRACOSTA'                :[WATER     , ROCK],
    'ARCHEN'                    :[ROCK      , FLYING],
    'ARCHETOPS'                 :[ROCK      , FLYING],
    'TRUBBISH'                  :[POISON    , NONE],
    'GARBODOR'                  :[POISON    , NONE],
    'ZORUA'                     :[DARK      , NONE],
    'ZORUA (HISUIAN)'           :[NORMAL    , GHOST],
    'ZOROARK'                   :[DARK      , NONE],
    'ZOROARK (HISUIAN)'         :[NORMAL    , GHOST],
    'MINCCINO'                  :[NORMAL    , NONE],
    'CINCCINO'                  :[NORMAL    , NONE],
    'GOTHITA'                   :[PSYCHIC   , NONE],
    'GOTHORITA'                 :[PSYCHIC   , NONE],
    'GOTHITELLE'                :[PSYCHIC   , NONE],
    'SOLOSIS'                   :[PSYCHIC   , NONE],
    'DUOSION'                   :[PSYCHIC   , NONE],
    'REUNICLUS'                 :[PSYCHIC   , NONE],
    'DUCKLETT'                  :[WATER     , FLYING],
    'SWANNA'                    :[WATER     , FLYING],
    'VANILLITE'                 :[ICE       , NONE],
    'VANILLISH'                 :[ICE       , NONE],
    'VANILLUXE'                 :[ICE       , NONE],
    'DEERLING (SPRING)'         :[NORMAL    , GRASS],
    'DEERLING (SUMMER)'         :[NORMAL    , GRASS],
    'DEERLING (AUTUMN)'         :[NORMAL    , GRASS],
    'DEERLING (WINTER)'         :[NORMAL    , GRASS],
    'SAWSBUCK (SPRING)'         :[NORMAL    , GRASS],
    'SAWSBUCK (SUMMER)'         :[NORMAL    , GRASS],
    'SAWSBUCK (AUTUMN)'         :[NORMAL    , GRASS],
    'SAWSBUCK (WINTER)'         :[NORMAL    , GRASS],
    'EMOLGA'                    :[ELECTRIC  , FLYING],
    'KARRABLAST'                :[BUG       , NONE],
    'ESCAVALIER'                :[BUG       , STEEL],
    'FOONGUS'                   :[GRASS     , POISON],
    'AMOONGUSS'                 :[GRASS     , POISON],
    'FRILLISH'                  :[WATER     , GHOST],
    'JELLICENT'                 :[WATER     , GHOST],
    'ALOMOMOLA'                 :[WATER     , NONE],
    'JOLTIK'                    :[BUG       , ELECTRIC],
    'GALVANTULA'                :[BUG       , ELECTRIC],
    'FERROSEED'                 :[GRASS     , STEEL],
    'FERROTHORN'                :[GRASS     , STEEL],
    'KLINK'                     :[STEEL     , NONE],
    'KLANG'                     :[STEEL     , NONE],
    'KLINKLANG'                 :[STEEL     , NONE],
    'TYNAMO'                    :[ELECTRIC  , NONE],
    'EELEKTRIK'                 :[ELECTRIC  , NONE],
    'EELEKTROSS'                :[ELECTRIC  , NONE],
    'ELGYEM'                    :[PSYCHIC   , NONE],
    'BEHEEYEM'                  :[PSYCHIC   , NONE],
    'LITWICK'                   :[GHOST     , FIRE],
    'LAMPERT'                   :[GHOST     , FIRE],
    'CHANDELURE'                :[GHOST     , FIRE],
    'AXEW'                      :[DRAGON    , NONE],
    'FRAXURE'                   :[DRAGON    , NONE],
    'HAXORUS'                   :[DRAGON    , NONE],
    'CUBCHOO'                   :[ICE       , NONE],
    'BEATRIC'                   :[ICE       , NONE],
    'CRYOGONAL'                 :[ICE       , NONE],
    'SHELMET'                   :[BUG       , NONE],
    'ACCELGOR'                  :[BUG       , NONE],
    'STUNFISK'                  :[GROUND    , ELECTRIC],
    'STUNFISK (GALARIAN)'       :[GROUND    , STEEL],
    'MIENFOO'                   :[FIGHTING  , NONE],
    'MIENSHAO'                  :[FIGHTING  , NONE],
    'DRUDDIGON'                 :[DRAGON    , NONE],
    'GOLETT'                    :[GROUND    , GHOST],
    'GOLURK'                    :[GROUND    , GHOST],
    'PAWNIARD'                  :[DARK      , STEEL],
    'BISHARP'                   :[DARK      , STEEL],
    'BOUFFALANT'                :[NORMAL    , NONE],
    'RUFFLET'                   :[NORMAL    , FLYING],
    'BRAVIARY'                  :[NORMAL    , FLYING],
    'BRAVIARY (HISUIAN)'        :[PSYCHIC   , FLYING],
    'VULLABY'                   :[DARK      , FLYING],
    'MANDIBUZZ'                 :[DARK      , FLYING],
    'HEATMOR'                   :[FIRE      , NONE],
    'DURANT'                    :[BUG       , STEEL],
    'DEINO'                     :[DARK      , DRAGON],
    'ZWELLOUS'                  :[DARK      , DRAGON],
    'HYDREIGON'                 :[DARK      , DRAGON],
    'LARVESTA'                  :[BUG       , FIRE],
    'VOLCARONA'                 :[BUG       , FIRE],
    'COBALION'                  :[STEEL     , FIGHTING],
    'TERRAKION'                 :[ROCK      , FIGHTING],
    'VIRIZION'                  :[GRASS     , FIGHTING],
    'TORNADUS (INCARNATE)'      :[FLYING    , NONE],
    'TORNADUS (THERIAN)'        :[FLYING    , NONE],
    'THUNDURUS (INCARNATE)'     :[ELECTRIC  , FLYING],
    'THUNDURUS (THERIAN)'       :[ELECTRIC  , FLYING],
    'RESHIRAM'                  :[DRAGON    , FIRE],
    'ZEKROM'                    :[DRAGON    , ELECTRIC],
    'LANDORUS (INCARNATE)'      :[GROUND    , FLYING],
    'LANDORUS (THERIAN)'        :[GROUND    , FLYING],
    'KYUREM'                    :[DRAGON    , ICE],
    'KYUREM (WHITE)'            :[DRAGON    , ICE],
    'KYUREM (BLACK)'            :[DRAGON    , ICE],
    'KELDEO (ORDINARY)'         :[WATER     , FIGHTING],
    'KELDEO (RESOLUTE)'         :[WATER     , FIGHTING],
    'MELOETTA (ARIA)'           :[NORMAL    , PSYCHIC],
    'MELOETTA (PIROUETTE)'      :[NORMAL    , FIGHTING],
    'GENESECT'                  :[BUG       , STEEL],
    'GENESECT (DOUSE)'          :[BUG       , STEEL],
    'GENESECT (SHOCK)'          :[BUG       , STEEL],
    'GENESECT (BURN)'           :[BUG       , STEEL],
    'GENESECT (CHILL)'          :[BUG       , STEEL],





    'CHESPIN'                   :[GRASS     , NONE],
    'QUILLADIN'                 :[GRASS     , NONE],
    'CHESNAUGHT'                :[GRASS     , FIGHTING],
    'FENNEKIN'                  :[FIRE      , NONE],
    'BRAIXEN'                   :[FIRE      , NONE],
    'DELPHOX'                   :[FIRE      , PSYCHIC],
    'FROAKIE'                   :[WATER     , NONE],
    'FROGADIER'                 :[WATER     , NONE],
    'GRENINJA'                  :[WATER     , DARK],
    'BUNNELBY'                  :[NORMAL    , NONE],
    'DIGGERSBY'                 :[NORMAL    , GROUND],
    'FLETCHLING'                :[NORMAL    , FLYING],
    'FLETCHINDER'               :[FIRE      , FLYING],
    'TALONFLAME'                :[FIRE      , FLYING],
    'SCATTERBUG'                :[BUG       , NONE],
    'SPEWPA'                    :[BUG       , NONE],
    'VIVILLON'                  :[BUG       , FLYING],
    'LITLEO'                    :[FIRE      , NORMAL],
    'PYROAR'                    :[FIRE      , NORMAL],
    'FLABEBE (RED)'             :[FAIRY     , NONE],
    'FLABEBE (YELLOW)'          :[FAIRY     , NONE],
    'FLABEBE (ORANGE)'          :[FAIRY     , NONE],
    'FLABEBE (BLUE)'            :[FAIRY     , NONE],
    'FLABEBE (WHITE)'           :[FAIRY     , NONE],
    'FLOETTE (RED)'             :[FAIRY     , NONE],
    'FLOETTE (YELLOW)'          :[FAIRY     , NONE],
    'FLOETTE (ORANGE)'          :[FAIRY     , NONE],
    'FLOETTE (BLUE)'            :[FAIRY     , NONE],
    'FLOETTE (WHITE)'           :[FAIRY     , NONE],
    'FLORGES (RED)'             :[FAIRY     , NONE],
    'FLORGES (YELLOW)'          :[FAIRY     , NONE],
    'FLORGES (ORANGE)'          :[FAIRY     , NONE],
    'FLORGES (BLUE)'            :[FAIRY     , NONE],
    'FLORGES (WHITE)'           :[FAIRY     , NONE],
    'SKIDDO'                    :[GRASS     , NONE],
    'GOGOAT'                    :[GRASS     , NONE],
    'PANCHAM'                   :[FIGHTING  , NONE],
    'PANGORO'                   :[FIGHTING  , DARK],
    'FURFROU (NORMAL)'          :[NORMAL    , NONE],
    'ESPURR'                    :[PSYCHIC   , NONE],
    'MEOWSTIC (MALE)'           :[PSYCHIC   , NONE],
    'MEOWSTIC (FEMALE)'         :[PSYCHIC   , NONE],
    'HONEDGE'                   :[STEEL     , GHOST],
    'DOUBLADE'                  :[STEEL     , GHOST],
    'AEGISLASH (SHIELD)'        :[STEEL     , GHOST],
    'AEGISLASH (BLADE)'         :[STEEL     , GHOST],
    'SPRITZEE'                  :[FAIRY     , NONE],
    'AROMATISSE'                :[FAIRY     , NONE],
    'SWIRLIX'                   :[FAIRY     , NONE],
    'SLURPUFF'                  :[FAIRY     , NONE],
    'INKAY'                     :[DARK      , PSYCHIC],
    'MALAMAR'                   :[DARK      , PSYCHIC],
    'BINACLE'                   :[ROCK      , WATER],
    'BARBARACLE'                :[ROCK      , WATER],
    'SKRELP'                    :[POISON    , WATER],
    'DRAGALGE'                  :[POISON    , DRAGON],
    'CLAUNCHER'                 :[WATER     , NONE],
    'CLAWITZER'                 :[WATER     , NONE],
    'HELIOPTILE'                :[ELECTRIC  , NORMAL],
    'HELIOLISK'                 :[ELECTRIC  , NORMAL],
    'TYRUNT'                    :[ROCK      , DRAGON],
    'TYRANTRUM'                 :[ROCK      , DRAGON],
    'AMAURA'                    :[ROCK      , ICE],
    'AURORUS'                   :[ROCK      , ICE],
    'SYLVEON'                   :[FAIRY     , NONE],
    'HAWLUCHA'                  :[FIGHTING  , FLYING],
    'DEDENNE'                   :[ELECTRIC  , FAIRY],
    'CARBINK'                   :[ROCK      , FAIRY],
    'GOOMY'                     :[DRAGON    , NONE],
    'SLIGGOO'                   :[DRAGON    , NONE],
    'SLIGGOO (HISUIAN)'         :[STEEL     , DRAGON],
    'GOODRA'                    :[DRAGON    , NONE],
    'GOODRA (HISUIAN)'          :[STEEL     , DRAGON],
    'KLEFKI'                    :[STEEL     , FAIRY],
    'PHANTUMP'                  :[GHOST     , GRASS],
    'TREVENANT'                 :[GHOST     , GRASS],
    'PUMPKABOO'                 :[GHOST     , GRASS],
    'GOURGEIST'                 :[GHOST     , GRASS],
    'BERGMITE'                  :[ICE       , NONE],
    'AVALUGG'                   :[ICE       , NONE],
    'AVALUGG (HISUIAN)'         :[ICE       , ROCK],
    'NOIBAT'                    :[FLYING    , DRAGON],
    'NOIVERN'                   :[FLYING    , DRAGON],
    'XERNEAS (NEUTRAL)'         :[FAIRY     , NONE],
    'XERNEAS (aCTIVE)'          :[FAIRY     , NONE],
    'YVELTAL'                   :[DARK      , FLYING],
    'ZYGARDE (10%)'             :[DRAGON    , GROUND],
    'ZYGARDE (50%)'             :[DRAGON    , GROUND],
    'ZYGARDE (COMPLETE)'        :[DRAGON    , GROUND],
    'DIANCIE'                   :[ROCK      , FAIRY],
    'HOOPA (CONFINED)'          :[PSYCHIC   , GHOST],
    'HOOPA (UNBOUND)'           :[PSYCHIC   , DARK],
    'VOLCANION'                 :[FIRE      , WATER],





    'ROWLET'                    :[GRASS     , FLYING],
    'DARTRIX'                   :[GRASS     , FLYING],
    'DECIDUEYE'                 :[GRASS     , GHOST],
    'DECIDUEYE (HISUIAN)'       :[GRASS     , FIGHTING],
    'LITTEN'                    :[FIRE      , NONE],
    'TORRACAT'                  :[FIRE      , NONE],
    'INCINEROAR'                :[FIRE      , DARK],
    'POPPLIO'                   :[WATER     , NONE],
    'BRIONNE'                   :[WATER     , NONE],
    'PRIMARINA'                 :[WATER     , FAIRY],
    'PIKIPEK'                   :[NORMAL    , FLYING],
    'TRUMBEAK'                  :[NORMAL    , FLYING],
    'TOUCANNON'                 :[NORMAL    , FLYING],
    'YUNGOOS'                   :[NORMAL    , NONE],
    'GUMSHOOS'                  :[NORMAL    , NONE],
    'GRUBBIN'                   :[BUG       , NONE],
    'CHARJABUG'                 :[BUG       , ELECTRIC],
    'VIKAVOLT'                  :[BUG       , ELECTRIC],
    'CRABRAWLER'                :[FIGHTING  , NONE],
    'CRABOMINABLE'              :[FIGHTING  , ICE],
    'ORICORIO (BAILE)'          :[FIRE      , FLYING],
    'ORICORIO (POM-POM)'        :[ELECTRIC  , FLYING],
    'ORICORIO (PA\'U)'          :[PSYCHIC   , FLYING],
    'ORICORIO (SENSU)'          :[GHOST     , FLYING],
    'CUTIEFLY'                  :[BUG       , FAIRY],
    'RIBOMBEE'                  :[BUG       , FAIRY],
    'ROCKRUFF'                  :[ROCK      , NONE],
    'LYCANROC (MIDDAY)'         :[ROCK      , NONE],
    'LYCANROC (MIDNIGHT)'       :[ROCK      , NONE],
    'LYCANROC (DUSK)'           :[ROCK      , NONE],
    'WISHIWASHI (SOLO)'         :[WATER     , NONE],
    'WISHIWASHI (SCHOOL)'       :[WATER     , NONE],
    'MAREANIE'                  :[POISON    , WATER],
    'TOXAPEX'                   :[POISON    , WATER],
    'MUDBRAY'                   :[GROUND    , NONE],
    'MUDSDALE'                  :[GROUND    , NONE],
    'DEWPIDER'                  :[WATER     , BUG],
    'ARAQUANID'                 :[WATER     , BUG],
    'FOMANTIS'                  :[GRASS     , NONE],
    'LURANTIS'                  :[GRASS     , NONE],
    'MORELULL'                  :[GRASS     , FAIRY],
    'SHIINOTIC'                 :[GRASS     , FAIRY],
    'SALANDIT'                  :[POISON    , FIRE],
    'SALAZZLE'                  :[POISON    , FIRE],
    'STUFFUL'                   :[NORMAL    , FIGHTING],
    'BEWEAR'                    :[NORMAL    , FIGHTING],
    'BOUNSWEET'                 :[GRASS     , NONE],
    'STEENEE'                   :[GRASS     , NONE],
    'TSAREENA'                  :[GRASS     , NONE],
    'COMFEY'                    :[FAIRY     , NONE],
    'ORANGURU'                  :[NORMAL    , PSYCHIC],
    'PASSIMIAN'                 :[FIGHTING  , NONE],
    'WIMPOD'                    :[BUG       , WATER],
    'GOLISOPOD'                 :[BUG       , WATER],
    'SANDYGAST'                 :[GHOST     , GROUND],
    'PALOSSAND'                 :[GHOST     , GROUND],
    'PYUKUMUKU'                 :[WATER     , NONE],
    'TYPE: NULL'                :[NORMAL    , NONE],
    'SYLVALLY'                  :[NORMAL    , NONE],
    'MINIOR (METEOR)'           :[ROCK      , FLYING],
    'MINIOR (RED)'              :[ROCK      , FLYING],
    'KOMALA'                    :[NORMAL    , NONE],
    'TURTONATOR'                :[FIRE      , DRAGON],
    'TOGEDEMARU'                :[ELECTRIC  , STEEL],
    'MIMIKYU (DISGUISED)'       :[GHOST     , FAIRY],
    'MIMIKYU (BUSTED)'          :[GHOST     , FAIRY],
    'BRUXISH'                   :[WATER     , PSYCHIC],
    'DRAMPA'                    :[NORMAL    , DRAGON],
    'DHELMISE'                  :[GHOST     , GRASS],
    'JANGMO-O'                  :[DRAGON    , NONE],
    'HAKAMO-O'                  :[DRAGON    , FIGHTING],
    'KOMMO-O'                   :[DRAGON    , FIGHTING],
    'TAPU KOKO'                 :[ELECTRIC  , FAIRY],
    'TAPU LELE'                 :[PSYCHIC   , FAIRY],
    'TAPU BULU'                 :[GRASS     , FAIRY],
    'TAPU FINI'                 :[WATER     , FAIRY],
    'COSMOG'                    :[PSYCHIC   , NONE],
    'COSMOEM'                   :[PSYCHIC   , NONE],
    'SOLGALEO'                  :[PSYCHIC   , STEEL],
    'LUNALA'                    :[PSYCHIC   , GHOST],
    'NIHILEGO'                  :[ROCK      , POISON],
    'BUZZWOLE'                  :[BUG       , FIGHTING],
    'PHEROMOSA'                 :[BUG       , FIGHTING],
    'XURKITREE'                 :[ELECTRIC  , NONE],
    'CELESTEELA'                :[STEEL     , FLYING],
    'KARTANA'                   :[GRASS     , STEEL],
    'GUZZLORD'                  :[DARK      , DRAGON],
    'NECROZMA'                  :[PSYCHIC   , NONE],
    'NECROZMA (DUSK MANE)'      :[PSYCHIC   , STEEL],
    'NECROZMA (DAWN MANE)'      :[PSYCHIC   , GHOST],
    'MAGEARNA'                  :[STEEL     , FAIRY],
    'MARSHADOW'                 :[FIGHTING  , GHOST],
    'POIPOLE'                   :[POISON    , NONE],
    'NAGANADEL'                 :[POISON    , DRAGON],
    'STAKATAKA'                 :[ROCK      , STEEL],
    'BLACEPHALON'               :[FIRE      , GHOST],
    'ZERAORA'                   :[ELECTRIC  , NONE],
    'MELTAN'                    :[STEEL     , NONE],
    'MELMETAL'                  :[STEEL     , NONE],





    'GROOKEY'                   :[GRASS     , NONE],
    'THWACKEY'                  :[GRASS     , NONE],
    'RILLABOOM'                 :[GRASS     , NONE],
    'SCORBUNNY'                 :[FIRE      , NONE],
    'RABOOT'                    :[FIRE      , NONE],
    'CINDERACE'                 :[FIRE      , NONE],
    'SOBBLE'                    :[WATER     , NONE],
    'DRIZZLE'                   :[WATER     , NONE],
    'INTELEON'                  :[WATER     , NONE],
    'SKWOVET'                   :[NORMAL    , NONE],
    'GREEDENT'                  :[NORMAL    , NONE],
    'ROOKIDEE'                  :[FLYING    , NONE],
    'CORVISQUIRE'               :[FLYING    , NONE],
    'CORVIKNIGHT'               :[FLYING    , STEEL],
    'BLIPBUG'                   :[BUG       , NONE],
    'DOTTLER'                   :[BUG       , PSYCHIC],
    'ORBEETLE'                  :[BUG       , PSYCHIC],
    'NICKIT'                    :[DARK      , NONE],
    'THIEVUL'                   :[DARK      , NONE],
    'GOSSIFLEUR'                :[GRASS     , NONE],
    'ELDEGOSS'                  :[GRASS     , NONE],
    'WOOLOO'                    :[NORMAL    , NONE],
    'DUBWOOL'                   :[NORMAL    , NONE],
    'CHEWTIE'                   :[WATER     , NONE],
    'DREDNAW'                   :[WATER     , ROCK],
    'YAMPER'                    :[ELECTRIC  , NONE],
    'BOLTUND'                   :[ELECTRIC  , NONE],
    'ROLYCOLY'                  :[ROCK      , NONE],
    'CARLKOL'                   :[ROCK      , FIRE],
    'COALOSSAL'                 :[ROCK      , FIRE],
    'APPLIN'                    :[GRASS     , DRAGON],
    'FLAPPLE'                   :[GRASS     , DRAGON],
    'APPLETUN'                  :[GRASS     , DRAGON],
    'SILICOBRA'                 :[GROUND    , NONE],
    'SANDACONDA'                :[GROUND    , NONE],
    'CRAMORANT'                 :[FLYING    , WATER],
    'CRAMORANT (GULPING)'       :[FLYING    , WATER],
    'CRAMORANT (GORGING)'       :[FLYING    , WATER],
    'ARROKUDA'                  :[WATER     , NONE],
    'BARRASKEWDA'               :[WATER     , NONE],
    'TOXEL'                     :[ELECTRIC  , POISON],
    'TOXTRICITY (AMPED)'        :[ELECTRIC  , POISON],
    'TOXTRICITY (LOW KEY)'      :[ELECTRIC  , POISON],
    'SIZZLIPEDE'                :[FIRE      , BUG],
    'CENTISKORCH'               :[FIRE      , BUG],
    'CLOBBOPUS'                 :[FIGHTING  , NONE],
    'GRAPPLOCT'                 :[FIGHTING  , NONE],
    'SINISTEA'                  :[GHOST     , NONE],
    'POLTEAGEIST'               :[GHOST     , NONE],
    'HATENNA'                   :[PSYCHIC   , NONE],
    'HATTREM'                   :[PSYCHIC   , NONE],
    'HATTERENE'                 :[PSYCHIC   , FAIRY],
    'IMPIDIMP'                  :[DARK      , FAIRY],
    'MORGREM'                   :[DARK      , FAIRY],
    'GRIMMSNARL'                :[DARK      , FAIRY],
    'OBSTAGOON'                 :[DARK      , NORMAL],
    'PERRSERKER'                :[STEEL     , NONE],
    'CURSOLA'                   :[GHOST     , NONE],
    'SIRFETCH\'D'               :[FIGHTING  , NONE],
    'MR. RIME'                  :[ICE       , PSYCHIC],
    'RUNERIGUS'                 :[GROUND    , GHOST],
    'MILCERY'                   :[FAIRY     , NONE],
    'ALCREMIE'                  :[FAIRY     , NONE],
    'FALINKS'                   :[FIGHTING  , NONE],
    'PINCURCHIN'                :[ELECTRIC  , NONE],
    'SNOM'                      :[ICE       , BUG],
    'FROSMOTH'                  :[ICE       , BUG],
    'STONJOURNER'               :[ROCK      , NONE],
    'EISCUE (ICE)'              :[ICE       , NONE],
    'EISCUE (NOICE)'            :[ICE       , NONE],
    'INDEEDEE (MALE)'           :[PSYCHIC   , NORMAL],
    'INDEEDEE (FEMALE)'         :[PSYCHIC   , NORMAL],
    'MORPEKO (FULL BELLY)'      :[ELECTRIC  , DARK],
    'MORPEKO (HANGRY)'          :[ELECTRIC  , DARK],
    'CUFANT'                    :[STEEL     , NONE],
    'COPPERAJAH'                :[STEEL     , NONE],
    'DRACOZOLT'                 :[ELECTRIC  , DRAGON],
    'ARCTOZOLT'                 :[ELECTRIC  , ICE],
    'DRACOVISH'                 :[WATER     , DRAGON],
    'ARCTOVISH'                 :[WATER     , ICE],
    'DURALUDON'                 :[STEEL     , DRAGON],
    'DREEPY'                    :[DRAGON    , GHOST],
    'DRAKLOAK'                  :[DRAGON    , GHOST],
    'DRAGAPULT'                 :[DRAGON    , GHOST],
    'ZACIAN (HERO)'             :[FAIRY     , NONE],
    'ZACIAN (CROWN)'            :[FAIRY     , STEEL],
    'ZAMAZENTA (HERO)'          :[FIGHTING  , NONE],
    'ZAMAZENTA (CROWN)'         :[FIGHTING  , STEEL],
    'ETERNATUS'                 :[POISON    , DRAGON],
    'KUBFU'                     :[FIGHTING  , NONE],
    'URSHIFU (SINGLE)'          :[FIGHTING  , DARK],
    'URSHIFU (RAPID)'           :[FIGHTING  , WATER],
    'ZARUDE'                    :[DARK      , GRASS],
    'REGIELEKI'                 :[ELECTRIC  , NONE],
    'REGIDRAGO'                 :[DRAGON    , NONE],
    'GLASTRIER'                 :[ICE       , NONE],
    'SPECTRIER'                 :[GHOST     , NONE],
    'CALYREX'                   :[PSYCHIC   , GRASS],
    'CALYREX (ICE)'             :[PSYCHIC   , ICE],
    'CALYREX (SHADOW)'          :[PSYCHIC   , GHOST],
    'WYDEER'                    :[NORMAL    , PSYCHIC],
    'KLEAVOR'                   :[BUG       , ROCK],
    'URSALUNA'                  :[GROUND    , NORMAL],
    'URSALUNA (BLOODMOON)'      :[GROUND    , NORMAL],
    'BASCULEGION (MALE)'        :[WATER     , GHOST],
    'BASCULEGION (FEMALE)'      :[WATER     , GHOST],
    'SNEASLER'                  :[FIGHTING  , POISON],
    'OVERQWIL'                  :[DARK      , POISON],
    'ENAMORUS (INCARNATE)'      :[FAIRY     , FLYING],
    'ENAMORUS (THERIAN)'        :[FAIRY     , FLYING],





    'SPRIGATITO'                :[GRASS     , NONE],
    'FLORAGATO'                 :[GRASS     , NONE],
    'MEOWSCARADA'               :[GRASS     , DARK],
    'FUECOCO'                   :[FIRE      , NONE],
    'CROCATOR'                  :[FIRE      , NONE],
    'SKELEDRIDGE'               :[FIRE      , GHOST],
    'QUAXLY'                    :[WATER     , NONE],
    'QUAXWELL'                  :[WATER     , NONE],
    'QUAQUAVAL'                 :[WATER     , FIGHTING],
    'LECHONK'                   :[NORMAL    , NONE],
    'OINKOLOGNE'                :[NORMAL    , NONE],
    'TAROUNTULA'                :[BUG       , NONE],
    'SPIDOPS'                   :[BUG       , NONE],
    'NYMBLE'                    :[BUG       , NONE],
    'LOKIX'                     :[BUG       , DARK],
    'PAWMI'                     :[ELECTRIC  , NONE],
    'PAWMO'                     :[ELECTRIC  , FIGHTING],
    'PAWMOT'                    :[ELECTRIC  , FIGHTING],
    'TANDEMAUS'                 :[NORMAL    , NONE],
    'MAUSHOLD (THREE)'          :[NORMAL    , NONE],
    'MAUSHOLD (FOUR)'           :[NORMAL    , NONE],
    'FIDOUGH'                   :[FAIRY     , NONE],
    'DACHSHBUN'                 :[FAIRY     , NONE],
    'SMOLIV'                    :[GRASS     , NORMAL],
    'DOLLIV'                    :[GRASS     , NORMAL],
    'ARBOLIVA'                  :[GRASS     , NORMAL],
    'SQUAWKABILLY (GREEN)'      :[NORMAL    , FLYING],
    'SQUAWKABILLY (BLUE)'       :[NORMAL    , FLYING],
    'SQUAWKABILLY (YELLOW)'     :[NORMAL    , FLYING],
    'SQUAWKABILLY (WHITE)'      :[NORMAL    , FLYING],
    'NACLI'                     :[ROCK      , NONE],
    'NACLSTACK'                 :[ROCK      , NONE],
    'GARGANACL'                 :[ROCK      , NONE],
    'CHARCADET'                 :[FIRE      , NONE],
    'ARMAROUGE'                 :[FIRE      , PSYCHIC],
    'CERULEDGE'                 :[FIRE      , GHOST],
    'TADBULB'                   :[ELECTRIC  , NONE],
    'BELLIBOLT'                 :[ELECTRIC  , NONE],
    'WATTREL'                   :[ELECTRIC  , FLYING],
    'KILOWATTREL'               :[ELECTRIC  , FLYING],
    'MASCHIFF'                  :[DARK      , NONE],
    'MABOSSTIFF'                :[DARK      , NONE],
    'SHROODLE'                  :[POISON    , NORMAL],
    'GRAFAIAI'                  :[POISON    , NORMAL],
    'BRAMBLIN'                  :[GRASS     , GHOST],
    'BRAMBLEGHAST'              :[GRASS     , GHOST],
    'TOEDSCOOL'                 :[GROUND    , GRASS],
    'TOEDSCRUEL'                :[GROUND    , GRASS],
    'KLAWF'                     :[ROCK      , NONE],
    'CAPSAKID'                  :[GRASS     , NONE],
    'SCOVILLAIN'                :[GRASS     , FIRE],
    'RELLOR'                    :[BUG       , NONE],
    'RABSCA'                    :[BUG       , PSYCHIC],
    'FLITTLE'                   :[PSYCHIC   , NONE],
    'ESPATHRA'                  :[PSYCHIC   , NONE],
    'TINKATINK'                 :[FAIRY     , STEEL],
    'TINKATUFF'                 :[FAIRY     , STEEL],
    'TINKATON'                  :[FAIRY     , STEEL],
    'WIGLETT'                   :[WATER     , NONE],
    'WUGTRIO'                   :[WATER     , NONE],
    'BOMBIRDIER'                :[FLYING    , DARK],
    'FINIZEN'                   :[WATER     , NONE],
    'PALAFIN (ZERO)'            :[WATER     , NONE],
    'PALAFIN (HERO)'            :[WATER     , NONE],
    'VAROOM'                    :[STEEL     , POISON],
    'REVAVROOM'                 :[STEEL     , POISON],
    'CYCLIZAR'                  :[DRAGON    , NORMAL],
    'ORTHWORM'                  :[STEEL     , NONE],
    'GLIMMET'                   :[ROCK      , POISON],
    'GLIMMORA'                  :[ROCK      , POISON],
    'GREAVARD'                  :[GHOST     , NONE],
    'HOUNDSTONE'                :[GHOST     , NONE],
    'FLAMIGO'                   :[FLYING    , NONE],
    'CETODDLE'                  :[ICE       , NONE],
    'CETITAN'                   :[ICE       , NONE],
    'VELUZA'                    :[WATER     , PSYCHIC],
    'DONDOZO'                   :[WATER     , NONE],
    'TATSUGIRI (CURLY)'         :[DRAGON    , WATER],
    'TATSUGIRI (DROOPY)'        :[DRAGON    , WATER],
    'TATSUGIRI (STRETCHY)'      :[DRAGON    , WATER],
    'ANNIHILAPE'                :[FIGHTING  , GHOST],
    'CLODSIRE'                  :[POISON    , GROUND],
    'FARIGIRAF'                 :[NORMAL    , PSYCHIC],
    'DUDUNSPARSE (TWO)'         :[NORMAL    , NONE],
    'DUDUNSPARSE (THREE)'       :[NORMAL    , NONE],
    'KINGAMBIT'                 :[DARK      , STEEL],
    'GREAT TUSK'                :[GROUND    , FIGHTING],
    'SCREAM TAIL'               :[FAIRY     , PSYCHIC],
    'BRUTE BONNET'              :[GRASS     , DARK],
    'FLUTTER MANE'              :[GHOST     , FAIRY],
    'SLITHER WING'              :[BUG       , FIGHTING],
    'SANDY SHOCKS'              :[ELECTRIC  , GROUND],
    'IRON TREADS'               :[GROUND    , STEEL],
    'IRON BUNDLE'               :[ICE       , WATER],
    'IRON HANDS'                :[FIGHTING  , ELECTRIC],
    'IRON JUGULIS'              :[DARK      , FLYING],
    'IRON MOTH'                 :[FIRE      , POISON],
    'iRON THORNS'               :[ROCK      , ELECTRIC],
    'FRIGIBAX'                  :[DRAGON    , ICE],
    'ARCTIBAX'                  :[DRAGON    , ICE],
    'BAXCALIBUR'                :[DRAGON    , ICE],
    'GIMMIGHOUL (CHEST)'        :[GHOST     , NONE],
    'GIMMIGHOUL (ROAMING)'      :[GHOST     , NONE],
    'GHOLDENGO'                 :[STEEL     , GHOST],
    'WO-CHIEN'                  :[DARK      , GRASS],
    'CHIEN-PAO'                 :[DARK      , ICE],
    'TING-LU'                   :[DARK      , GROUND],
    'CHI-YU'                    :[DARK      , FIRE],
    'ROARING MOON'              :[DRAGON    , DARK],
    'IRON VALIANT'              :[FAIRY     , FIGHTING],
    'KORAIDON'                  :[FIGHTING  , DRAGON],
    'MIRAIDON'                  :[ELECTRIC  , DRAGON],
    'WALKING WAKE'              :[WATER     , DRAGON],
    'IRON LEAVES'               :[GRASS     , PSYCHIC],
    'DIPPLIN'                   :[GRASS     , DRAGON],
    'POLTCHAGEIST'              :[GRASS     , GHOST],
    'SINISTCHA'                 :[GRASS     , GHOST],
    'OKIDOGI'                   :[POISON    , FIGHTING],
    'MUNKIDORI'                 :[POISON    , FAIRY],
    'FEZANDIPITI'               :[POISON    , FAIRY],
    'OGERPON (TEAL)'            :[GRASS     , NONE],
    'OGERPON (WELLSPRING)'      :[GRASS     , WATER],
    'OGERPON (HEARTHFLAME)'     :[GRASS     , FIRE],
    'OGERPON (CORNERSTONE)'     :[GRASS     , ROCK],
    'ARCHALUDON'                :[STEEL     , DRAGON],
    'HYDRAPPLE'                 :[GRASS     , DRAGON],
    'GOUGING FIRE'              :[FIRE      , DRAGON],
    'RAGING BOLT'               :[ELECTRIC  , DRAGON],
    'IRON BOULDER'              :[ROCK      , PSYCHIC],
    'IRON CROWN'                :[STEEL     , PSYCHIC],
    'TERAPAGOS (NORMAL)'        :[NORMAL    , NONE],
    'TERAPAGOS (TERASTAL)'      :[NORMAL    , NONE],
    'PECHARUNT'                 :[POISON    , GHOST],
}

def compare_type_pairs(t1, t2):
    return (t1[0] == t2[0] and t1[1] == t2[1]) or (t1[0] == t2[1] and t1[1] == t2[0])


def sanitize_pair(pair):
    if pair[0] > pair[1]:
        return [pair[1], pair[0]]
    else:
        return [pair[0], pair[1]]


def type_pair_hash(pair):
    assert len(pair) == 2
    pair = sanitize_pair(pair)
    return "[" + str(pair[0]) + "," + str(pair[1]) + "]"


TYPE_PAIRS = {}
for t1 in range(0, len(TYPES)):
    for t2 in range(t1 + 1, len(TYPES)):
        pair = sanitize_pair([TYPES[t1], TYPES[t2]])
        hash = type_pair_hash(pair)
        TYPE_PAIRS[hash] = pair




REAL_TYPE_PAIRS = {}
for k, v in POKEMON_DB.items():
    hash = type_pair_hash(v)
    REAL_TYPE_PAIRS[hash] = v




TYPE_HISTOGRAM = {}

# Bump the counts on each pokemon's type
for k, v in POKEMON_DB.items():
    hash = type_pair_hash(v)
    if hash in TYPE_HISTOGRAM.keys():
        TYPE_HISTOGRAM[hash] += 1
    else:
        TYPE_HISTOGRAM[hash] = 1

    assert hash in TYPE_PAIRS.keys()

# Register counts for types that don't have any Pokemon
for h, p in TYPE_PAIRS.items():
    if not h in TYPE_HISTOGRAM.keys():
        TYPE_HISTOGRAM[h] = 0

TYPE_HISTOGRAM = dict(sorted(TYPE_HISTOGRAM.items(), key=lambda kv:kv[1]))
