NONE = ''
BUG = 'BUG'
DARK = 'DARK'
DRAGON = 'DRAGON'
ELECTRIC = 'ELECTRIC'
FAIRY = 'FAIRY'
FIGHTING = 'FIGHTING'
FIRE = 'FIRE'
FLYING = 'FLYING'
GHOST = 'GHOST'
GRASS = 'GRASS'
GROUND = 'GROUND'
ICE = 'ICE'
NORMAL = 'NORMAL'
POISON = 'POISON'
PSYCHIC = 'PSYCHIC'
ROCK = 'ROCK'
STEEL = 'STEEL'
WATER = 'WATER'

TYPES = [
    NONE,
    BUG,
    DARK,
    DRAGON,
    ELECTRIC,
    FAIRY,
    FIGHTING,
    FIRE,
    FLYING,
    GHOST,
    GRASS,
    GROUND,
    ICE,
    NORMAL,
    POISON,
    PSYCHIC,
    ROCK,
    STEEL,
    WATER]

WEAKNESSES = {
    NONE:[],
    BUG:[FIRE, FLYING, ROCK],
    DARK:[BUG, FAIRY, FIGHTING],
    DRAGON:[DRAGON, FAIRY, ICE],
    ELECTRIC:[GROUND],
    FAIRY:[POISON, STEEL],
    FIGHTING:[FAIRY, FLYING, PSYCHIC],
    FIRE:[GROUND, ROCK, WATER],
    FLYING:[ELECTRIC, ICE, ROCK],
    GHOST:[DARK, GHOST],
    GRASS:[BUG, FIRE, FLYING, ICE, POISON],
    GROUND:[GRASS, ICE, WATER],
    ICE:[FIGHTING, FIRE, ROCK, STEEL],
    NORMAL:[FIGHTING],
    POISON:[GROUND, PSYCHIC],
    PSYCHIC:[BUG, DARK, GHOST],
    ROCK:[FIGHTING, GRASS, GROUND, STEEL, WATER],
    STEEL:[FIGHTING, FIRE, GROUND],
    WATER:[ELECTRIC, GRASS]}

RESISTANCES = {
    NONE:[],
    BUG:[FIGHTING, GRASS, GROUND],
    DARK:[DARK, GHOST, PSYCHIC],
    DRAGON:[ELECTRIC, FIRE, GRASS, WATER],
    ELECTRIC:[ELECTRIC, FLYING, STEEL],
    FAIRY:[BUG, DARK, DRAGON, FIGHTING],
    FIGHTING:[BUG, DARK, ROCK],
    FIRE:[BUG, FAIRY, FIRE, GRASS, ICE, STEEL],
    FLYING:[BUG, FIGHTING, GRASS, GROUND],
    GHOST:[BUG, FIGHTING, NORMAL, NORMAL],
    GRASS:[ELECTRIC, GRASS, GROUND, WATER],
    GROUND:[ELECTRIC, POISON, ROCK],
    ICE:[ICE],
    NORMAL:[GHOST],
    POISON:[BUG, FAIRY, FIGHTING, GRASS, POISON],
    PSYCHIC:[FIGHTING, PSYCHIC],
    ROCK:[FIRE, FLYING, NORMAL, POISON],
    STEEL:[BUG, DRAGON, FAIRY, FLYING, GRASS, ICE, NORMAL, POISON, PSYCHIC, ROCK, STEEL],
    WATER:[FIRE, ICE, STEEL, WATER]}